# docker-compose for local development
version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: /bin/sh -c "yarn dev"
